name: dbdocs

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
    branches: [main]
    paths:
      - sample.dbml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.state == 'closed' && 'main' || github.head_ref }}

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      - name: Build dbdocs
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build sample.dbml